const actionTypes = {
  GET_ALL_CONTENT_TEXTS_BY_TYPE: 'GET_ALL_CONTENT_TEXTS_BY_TYPE',
  GET_ALL_TEAM_RESOURCES: 'GET_ALL_TEAM_RESOURCES',
  GET_ALL_INFRASTRUCTURE_REQUIREMENTS: 'GET_ALL_INFRASTRUCTURE_REQUIREMENTS',
  GET_ALL_DISK_DRIVES: 'GET_ALL_DISK_DRIVES',
};

export default actionTypes;
